

// src/services/ExportService.ts
import { File } from '../types';
import archiver from 'archiver';

const generateReadme = (projectTitle: string): string => {
  return `# ${projectTitle}

## Generated by AI Code Generation Platform

This project was generated using AI. To use:

1. Open \`index.html\` in a web browser
2. Or serve the files using a local server:
   \`\`\`bash
   npx serve .
   \`\`\`

## Files Included

- HTML files: Main structure
- CSS files: Styling
- JavaScript files: Functionality

## Notes

- This is a basic implementation
- You may need to customize for production use
- Test thoroughly before deploying

---
Generated on ${new Date().toISOString()}
`;
};

export const exportAsZip = async (files: File[], projectTitle: string): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const archive = archiver('zip', { zlib: { level: 9 } });
    const chunks: Buffer[] = [];

    archive.on('data', (chunk) => chunks.push(chunk));
    archive.on('end', () => resolve(Buffer.concat(chunks)));
    archive.on('error', reject);

    // Add files to archive
    files.forEach(file => {
      archive.append(file.content, { name: file.filename });
    });

    // Add README
    const readme = generateReadme(projectTitle);
    archive.append(readme, { name: 'README.md' });

    archive.finalize();
  });
};